---
train: "Jets_EMC_PbPb"
trainNumber: 3072
ptHardBin: 1
production: "LHC11h"
embeddedProduction: "LHC12a15e_fix"
alienOutputDir: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb//merge_runlist_1"
status: "Test of a single pt hard bin"
