---
train: "Jets_EMC_PbPb"
trainNumber: 2248
ptHardBin: 2
production: "LHC11h"
embeddedProduction: "LHC12a15e_fix"
alienOutputDir: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/2248_20170718-1330/merge_runlist_1"
status: ""
