---
repos:
    - repo: "https://gitlab.com/pycqa/flake8"
      rev: 3.7.7  # 3.6.0 doesn't contain this configuration file.
      hooks:
          - id: flake8
            additional_dependencies: ["flake8-colors"]
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.15.0
      hooks:
          - id: yamllint
    # Use local mypy instead of the standard hook because we need other packages
    # (ie. pachyderm and reaction_plane_fit). Otherwise, mypy will fail because
    # it doesn't recognize the classes and types.
    - repo: local
      hooks:
          - id: system
            name: mypy
            entry: mypy
            language: system
            types: [python]
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.3.0
      hooks:
          - id: python-check-mock-methods
          - id: rst-backticks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.2.1
      hooks:
          - id: trailing-whitespace
          - id: check-executables-have-shebangs
