---
train: "Jets_EMC_PbPb"
trainNumber: 2256
ptHardBin: 10
production: "LHC11h"
embeddedProduction: "LHC12a15e_fix"
alienOutputDir: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/2256_20170719-0112/merge_runlist_1"
status: ""
