---
train: "Jets_EMC_PbPb"
trainNumber: 2129
ptHardBin: 2
production: "LHC11h"
embeddedProduction: "LHC12a15e_fix"
alienOutputDir: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/2129_20170529-1707/merge_runlist_1"
