---
train: "Jets_EMC_PbPb"
trainNumber: 2706
ptHardBin: 6
production: "LHC11h"
embeddedProduction: "LHC12a15e_fix"
alienOutputDir: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/2706_20171111-0633/merge_runlist_1"
status: ""
