---
train: "Jets_EMC_PbPb"
trainNumber: 2707
ptHardBin: 7
production: "LHC11h"
embeddedProduction: "LHC12a15e_fix"
alienOutputDir: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/2707_20171111-0635/merge_runlist_1"
status: ""
