---
train: "Jets_EMC_PbPb"
trainNumber: 3231
production: "LHC11h"
embeddedProduction: "LHC11a"
alienOutputDir: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/3231_20180306-0652/merge_runlist_1"
status: "5 GeV Track Bias"
