---
train: "Jets_EMC_PbPb"
trainNumber: 4765
production: "LHC15o"
alienOutputDir: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/4765"
status: |
    "Jet-hadron correlations at 5 TeV with a 5 GeV track bias. Includes z vertex dependence for mixed event"
    "acceptance systematics."
