---
train: "Jets_EMC_PbPb"
trainNumber: 2135
ptHardBin: 9
production: "LHC11h"
embeddedProduction: "LHC12a15e_fix"
alienOutputDir: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/2135_20170529-1812/merge_runlist_1"
