---
train: "Jets_EMC_PbPb"
trainNumber: 2252
ptHardBin: 6
production: "LHC11h"
embeddedProduction: "LHC12a15e_fix"
alienOutputDir: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/2252_20170718-1710/merge_runlist_1"
status: ""
