---
train: "Jets_EMC_PbPb"
trainNumber: 2028
ptHardBin: 4
production: "LHC11h"
embeddedProduction: "LHC12a15e_fix"
alienOutputDir: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/2028_20170426-1612/merge_runlist_1"
