---
train: "Jets_EMC_PbPb"
trainNumber: 4754
production: "LHC15o"
embeddedProduction: "LHC16j5"
ptHardBin: 17
alienOutputDir: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/4754_20190906-2332/merge"
status: |
    "Response matrix for 0-10% and 30-50% in LHC15o. Uses matching in the Jet-H performance task, which appears to "
    "work around the job failure issues."
