---
train: "Jets_EMC_PbPb"
trainNumber: 2254
ptHardBin: 8
production: "LHC11h"
embeddedProduction: "LHC12a15e_fix"
alienOutputDir: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/2254_20170718-1903/merge_runlist_1"
status: ""
