---
train: "Jets_EMC_PbPb"
trainNumber: 3548
production: "LHC11h"
embeddedProduction: "LHC12a15e"
ptHardBin: 2
alienOutputDir: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/3548_20180413-1612/merge_runlist_1"
status: "Response matrix for 0-10% (ie using .98 for the efficiency). Created using the Jet Response Maker."
