---
name: "Configuration options for Jet-H Performance task for LHC15o PbPb."
enable:
    QAHists: true
    responseMatrix: false
eventCuts:
    enabled: true
    manualMode: true
    cutsPeriod: &period "LHC15o"
    centralityRange: [30, 50]
    enablePileupCuts: true
general:
    nCentBins: 5
efficiency:
    periodIdentifier: *period
QA:
    cellsName: "emcalCells"
# Cluster collections
clusters:
    clustersForJets:
        branchName: "usedefault"
        defaultEnergy: kHadCorr
        minE: 3
# Particle collections:
particles:
    tracksForCorrelations:
        branchName: "usedefault"
    tracksForJets:
        branchName: "usedefault"
        minPt: 3
# Jet collections
jets:
    leadingHadronBiasType: &leadingHadronType kCharged
    analysisJets:
        # High constituent cut
        collection: "Jet_AKTFullR020_tracks_pT3000_caloClusters_E3000_pt_scheme"
        # Low constituent cut
        #collection: "Jet_AKTFullR020_tracks_pT0150_caloClusters_E0300_pt_scheme"
        acceptance:
            - "kEMCALfid"
        R: &R 0.2
        areaCutPercentage: 0.6
        # Uncomment for rho subtraction
        #rhoName: "Rho_Scaled"
# Configure response matrix
responseMatrix:
    minFractionSharedPt: 0.5
    useThreeJetCollections: false
    axes:
        # Define the dimnesions that we are interested in
        # Format is ["name", [nBins, min, max]]
        - ["p_{T,1}", [250, 0, 250]]
        - ["p_{T,2}", [250, 0, 250]]
        - ["A_{jet,1}", [60, 0, 1.5]]
        - ["A_{jet,2}", [60, 0, 1.5]]
        - ["distance", [40, 0, 0.4]]
        - ["p_{T,particle,1}^{leading} (GeV/c)", [100, 0, 100]]
        - ["p_{T,particle,2}^{leading} (GeV/c)", [100, 0, 100]]
        - ["#theta_{jet,1}^{EP}", [3, 0, 1.570796]]  # max = pi/2
        - ["#theta_{jet,2}^{EP}", [3, 0, 1.570796]]  # max = pi/2
