---
train: "Jets_EMC_PbPb"
trainNumber: 4752
production: "LHC15o"
embeddedProduction: "LHC16j5"
ptHardBin: 15
alienOutputDir: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/4752_20190906-2322/merge"
status: |
    "Response matrix for 0-10% and 30-50% in LHC15o. Uses matching in the Jet-H performance task, which appears to "
    "work around the job failure issues."
