---
train: "Jets_EMC_PbPb"
trainNumber: 2734
production: "LHC11h"
embeddedProduction: "LHC11a"
alienOutputDir: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/2734_20171118-0228/merge_runlist_1"
status: |
    "Test without applying the tracking efficiency. Event selection mismatch between"
    "pp and Pb--Pb depleted statistics."
