---
# Used to override the standard embedding LHC11h configuration
internalEventSelection:
    centralityRange: [30, 50]
    physicsSelection:
        - "kAnyINT"
        - "KSemiCentral"
        - "kEMCEGA"  # For the GA trigger in Joel's analysis
