---
name: "Override options for response matrix for semi-central collisions"
eventCuts:
    centralityRange: [30, 50]
# Jet collections
jets:
    hybridLevelJets:
        collection: "hybridLevelJets_semiCentral_AKTFullR020_tracks_pT3000_caloClustersCombined_E3000_pt_scheme"
