---
name: "Configuration options for Jet-H Performance task for embedding pp data"
# Jet collections
jets:
    R: &R 0.2
    leadingHadronBiasType: &leadingHadronType kNeutral
    hybridLevelJets:
        collection: "hybridLevelJets_AKTFullR020_tracks_pT3000_caloClustersCombined_E3000_pt_scheme"
        acceptance:
            - "kEMCALfid"
        R: *R
    detLevelJets:
        collection: "detLevelJets_AKTFullR020_tracks_pT3000_caloClusters_E3000_pt_scheme"
        acceptance:
            - "kEMCALfid"
        R: *R
# Configure response matrix
responseMatrix:
    useThreeJetCollections: false
