---
train: "Jets_EMC_PbPb"
trainNumber: 2251
ptHardBin: 5
production: "LHC11h"
embeddedProduction: "LHC12a15e_fix"
alienOutputDir: "/alice/cern.ch/user/a/alitrain/PWGJE/Jets_EMC_PbPb/2251_20170718-1609/merge_runlist_1"
status: ""
